Repository cloud-club/90DaysOfDevOps, pull requests merged in 2023-10, with the labels that each got.

#12 5. Containers & 6. Kubernetes
  2주차/한지훈.md
Labels: needs review

#20 5. Containers & 6. Kubernetes
  2주차/박서연.md
Labels: needs review

#25 9. Learn Infrastructure as Code & 10. Automate Configuration Management
  3주차/이주연.md
Labels: needs review

#13 Learn Infrastructure as Code & Automate Configuration Management
  3주차/한지훈.md
  3주차/한지훈.tmi.md
Labels: needs review

#22 1. What is and why do we use DevOps & 4. Understand Networking
  1주차/seul/DevOps_Lifecycle.png
  1주차/이슬.md
Labels: needs review, approval + 2

#23 9. Learn Infrastructure as Code & 10. Automate Configuration Management
  3주차/김수민.md
Labels: needs review

#24 5. Containers & 6. Kubernetes
  2주차/이주연.md
Labels: needs review, approval + 2

#33 9. Learn Infrastructure as Code & 10. Automate Configuration Management
  3주차/image-1.png
  3주차/image-2.png
  3주차/image.png
  3주차/박서연.md
Labels: needs review

#36 11. Create CI/CD Pipelines & 12.Monitoring, Log Management, and Data Visualisation
  4주차/seoyeonImg/image-1.png
  4주차/seoyeonImg/image-10.png
  4주차/seoyeonImg/image-11.png
  4주차/seoyeonImg/image-12.png
  4주차/seoyeonImg/image-13.png
  4주차/seoyeonImg/image-14.png
  4주차/seoyeonImg/image-15.png
  4주차/seoyeonImg/image-16.png
  4주차/seoyeonImg/image-17.png
  4주차/seoyeonImg/image-18.png
  4주차/seoyeonImg/image-19.png
  4주차/seoyeonImg/image-2.png
  4주차/seoyeonImg/image-20.png
  4주차/seoyeonImg/image-21.png
  4주차/seoyeonImg/image-22.png
  4주차/seoyeonImg/image-23.png
  4주차/seoyeonImg/image-24.png
  4주차/seoyeonImg/image-25.png
  4주차/seoyeonImg/image-26.png
  4주차/seoyeonImg/image-27.png
  4주차/seoyeonImg/image-28.png
  4주차/seoyeonImg/image-29.png
  4주차/seoyeonImg/image-3.png
  4주차/seoyeonImg/image-30.png
  4주차/seoyeonImg/image-31.png
  4주차/seoyeonImg/image-32.png
  4주차/seoyeonImg/image-33.png
  4주차/seoyeonImg/image-34.png
  4주차/seoyeonImg/image-35.png
  4주차/seoyeonImg/image-36.png
  4주차/seoyeonImg/image-37.png
  4주차/seoyeonImg/image-38.png
  4주차/seoyeonImg/image-39.png
  4주차/seoyeonImg/image-4.png
  4주차/seoyeonImg/image-40.png
  4주차/seoyeonImg/image-41.png
  4주차/seoyeonImg/image-42.png
  4주차/seoyeonImg/image-43.png
  4주차/seoyeonImg/image-44.png
  4주차/seoyeonImg/image-45.png
  4주차/seoyeonImg/image-46.png
  4주차/seoyeonImg/image-47.png
  4주차/seoyeonImg/image-48.png
  4주차/seoyeonImg/image-49.png
  4주차/seoyeonImg/image-5.png
  4주차/seoyeonImg/image-6.png
  4주차/seoyeonImg/image-7.png
  4주차/seoyeonImg/image-8.png
  4주차/seoyeonImg/image-9.png
  4주차/seoyeonImg/image.png
  4주차/박서연.md
Labels: needs review

#28 11. Create CI/CD Pipelines & 12.Monitoring, Log Management, and Data Visualisation
  4주차/김수민.md
Labels: needs review

#39 13.Store & Protect Your Data & 1.DevSecOps
  5주차/image-1.png
  5주차/image-10.png
  5주차/image-11.png
  5주차/image-12.png
  5주차/image-2.png
  5주차/image-3.png
  5주차/image-4.png
  5주차/image-5.png
  5주차/image-6.png
  5주차/image-7.png
  5주차/image-8.png
  5주차/image-9.png
  5주차/image.png
  5주차/박서연.md
Labels: approval + 2
